### ISSUE TITLE
dlopen failed: library "libaaudio.so" not found

### ISSUE THREAD

**Issue by GunNan** [googlesamples/android-audio-high-performance#48]
A crash happened when I run the "hello-aaudio" project.

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                 Process: com.google.sample.com.google.sample.aaudio.play, PID: 27133
                                                                                                 
java.lang.UnsatisfiedLinkError: dlopen failed: library "libaaudio.so" not found
                                                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                                                                     at com.google.sample.aaudio.play.MainActivity.<clinit>(MainActivity.java:92)
                                                                                                     at java.lang.Class.newInstance(Native Method)
                                                                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1095)
                                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3083)
                                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by ggfan** [comment]
this is same as: 
https://github.com/googlesamples/android-audio-high-performance/issues/47
